
@login = http://localhost:3000/user/login
@signup = http://localhost:3000/user/signup
@listRecipes =http://localhost:3000/user/recipes
@addRecipe = http://localhost:3000/user/recipes
@getRecipeById = http://localhost:3000/recipes
@logout =   http://localhost:3000/user/logout
### Login
POST {{login}}
Content-Type: application/json

{
    "email" : "newuser@example2.com",
    "password" : "password1234"
}

### Sign Up
POST {{signup}}
Content-Type: application/json

{
    "username" : "newuser",
    "email" : "newuser@example2.com",
    "password" : "password1234"
}

### List Recipes (Requires Authentication)
GET {{listRecipes}}
Auth:   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6Im5ld3VzZXJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpYXQiOjE3MjYyNDM3NDIsImV4cCI6MTc4NjI0Mzc0Mn0.BmWP_L-tRdQekXPTpxWWI3U_sAiG0Epx-HZ7cAhhlQA###

### Add Recipe (Requires Authentication)
POST {{addRecipe}}
Content-Type: application/json
Auth:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6Im5ld3VzZXJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpYXQiOjE3MjYyNDM3NDIsImV4cCI6MTc4NjI0Mzc0Mn0.BmWP_L-tRdQekXPTpxWWI3U_sAiG0Epx-HZ7cAhhlQA

{
    "title" : "Delicious Pancakes5",
    "description" : "Fluffy pancakes with syrup.",
    "ingredients" : "Flour, Eggs, Milk, Sugar",
    "instructions" : "Mix ingredients and cook on a griddle.",
    "cooking_time" : 1500,
    "difficulty" : "Easy"
}

### Get Recipe By ID
GET {{getRecipeById}}/1
Content-Type: application/json
Auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6Im5ld3VzZXJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpYXQiOjE3MjYyNDM3NDIsImV4cCI6MTc4NjI0Mzc0Mn0.BmWP_L-tRdQekXPTpxWWI3U_sAiG0Epx-HZ7cAhhlQA
### log out


POST {{logout}}
Content-Type: application/json
Auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6Im5ld3VzZXJAZXhhbXBsZS5jb20iLCJ1c2VybmFtZSI6Im5ld3VzZXIiLCJpYXQiOjE3MjYyNDM3NDIsImV4cCI6MTc4NjI0Mzc0Mn0.BmWP_L-tRdQekXPTpxWWI3U_sAiG0Epx-HZ7cAhhlQA